import type { NextPage } from "next";
import Head from "next/head";
import ProductDetails from "components/ProductDetails";

const PDP: NextPage = () => (
  <div className="container">
    <Head>
      <title>RTG Frontend technical assessment</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="main">
      <h1>RTG Front-end technical assessment</h1>
      <ProductDetails />
    </main>
  </div>
);

export default PDP;
